### ISSUE TITLE
Clarification for the undergrads

### ISSUE THREAD

**Issue by LegyPlegy** [umd-lhcb/gbtx_brds_doc#11]
Bullet list for suggestions from first training day. More to follow upon further revisions. Feel free to ask for more clarification.

### Safety
- [x] Add "Inspect every single set of male and female pins after each and every connection and disconnection. Emphasize looking for bent or broken pins, foreign objects, dust, etc."
- [x] Add "Always ensure that the power supply has the correct voltage/amperage in Channels 1 & 3 - Channel 1 should be 1.5V/2.5A and Channel 3 should be 2.5V/1A"

#### 2.1
 - [x] suggest to move section 2.1 to an appendix, unnecessary since GBTx DB are no longer used
#### 2.2.1
 - [x] First paragraph very unclear. What is SALT elink data, and what is the counting room? 
 - [x] Add link to appendix C for PRBS in footnotes
 - [x] Perhaps include a paragraph explaining what each part refers to. Fig. 2.2.1 is a picture of the DCB, Fig 2.2.2 is a picture of the power breakout board. Add a photo of the mezzanine and reference it as 2.2.3. 

#### 2.2.2
~~the "power" label not visible at all on the printed black/white documentation. maybe point this out?~~

#### 2.2.3
~~Suggest adding a photo of a correctly-seated flexible tape connection. Some of the flexible tapes have been cut slightly diagonally which makes it difficult to tell by eye.~~

#### 3.1
 - [x] We noticed an issue while training that the legacy WinCC instructions are immediately preceding the new GBTX Programmer instructions. These should be put in separate sections or at least they should be labeled with bold text to minimize confusion
 - [x] "Load a configuration file" is vague, suggest adding a file path to where the master.txt is located on github, specifying that 3.1 refers to the master.txt and 3.2 refers to slave-Tx.txt. (Path is /home/Public/, visible in fig 3.4.1)

#### 3.2
 - [x] Add a section for launching WinCC 3.1.5 (suggested by Yipeng)
 - [x] To enhance readability, perhaps we can split up the instructions by the computer they need to be done on? There is a lot of swapping that is not obvious from the documentation

#### 3.3
 - [x] The documentation refers to "Activate Channel" as a troubleshoot. Should this now be standard procedure?

#### 3.4 
- [x] a small introduction here would be good to explain what the difference between programming the master and slave is. We made the mistake ourselves of mixing up the configuration files!

#### 3.5
- [x] Add a line saying that this is a preferred method to reseting the GBTxs instead of power cycling them or reconnecting them.

#### B Bypass components in GBT data path
- [x] Move the footnote superscript outside of the parenthesis, at first glance it looks like an exponent.

#### C PRBS tests
- [x] a more detailed introduction would be good- what purpose PRBS tests serve, the different uses for Test 1 and Test 2

#### F On the cross-jumped DCB pins
- [x] add another subnote dedicated to the issues we had today regarding the issues with the SCA adapter and being resolved by reconnecting these jumpers

**Comment by yipengsun** [comment]
For starters, we can drop the GBT DB subsection all together. Since all previous releases are publicly available, we can ask people to refer to the old version if they still want instructions for the GBT DB.

**Comment by yipengsun** [comment]
Also, there already is a link to power breakout board. Note that this pdf contains lots of links, try clicking on one of the "Figure x.y.z", and your pdf reader should take you to the actual figure.

**Comment by yipengsun** [comment]
For the "power" label, I don't have a good idea on how to fix it, other than print the documentation in color?

**Comment by yipengsun** [comment]
I don't think it is easy to take a picture of properly seated FFC cable. Can we try to describe it with words?

**Comment by yipengsun** [comment]
For the last point: Yesterday's issue was unrelated to the SCA jumpers, because SCA should work out of the box, provided that master GBTx is configured correctly.

We were unable to communicate with SCA purely because I chose the wrong configuration file for the master GBTx.

**Comment by yipengsun** [comment]
The suggestions listed in **3.2** have been updated in the `lab-notes` wiki. They are available [here](https://github.com/umd-lhcb/lab-notes/wiki/DCB-cheatsheet).
